  name: PullRepo

on:
  push:
    branches: [ "prod" ]

permissions:
  contents: read

jobs:

  updateSite:
    runs-on: ["Linux", "self-hosted"]
  
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'I-D-I-O-T-S-S/website'
          lfs: true
            
