name: PullRepo

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: [Linux, self-hosted]
  
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: 'I-D-I-O-T-S-S/website'
          lfs: true
            
